joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

screen_tilt_controller:
  type: position_controllers/JointPositionController
  joint: head_screen_tilt_joint

pan_controller:
  type: position_controllers/JointPositionController
  joint: head_pan_joint

tilt_controller:
  type: position_controllers/JointPositionController
  joint: head_tilt_joint