joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

# wheel1_controller:
#   type: velocity_controllers/JointVelocityController
#   joint: omni_wheel_1_joint

# wheel2_controller:
#   type: velocity_controllers/JointVelocityController
#   joint: omni_wheel_2_joint

# wheel3_controller:
#   type: velocity_controllers/JointVelocityController
#   joint: omni_wheel_3_joint

omni_base_controller:
  type: omni_drive_controller/OmniDriveController
  wheel1: omni_wheel_1_joint
  wheel2: omni_wheel_3_joint
  wheel3: omni_wheel_2_joint
  wheel_separation: 0.282
  wheel_radius: 0.0635
  publish_cmd: false
  publish_wheel_joint_controller_state: false
  publish_rate: 50.0
  pose_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
  twist_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
  cmd_vel_timeout: 20.0

